#Nombre de la actions
name: run_testCY

#Donde se va a correr
on: [push]

#El area de trabajo a ejecutar
jobs: 
 cypress-run:
    runs-on: ubuntu-lastest

#Los pasos a realizar donde va a ir las action del area de trabajo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress.io
        uses: cypress-io/github-action@v6
        with:
          start: npm start
